#!/bin/sh

# Exit from the script if any statement returns non-true
set -e

if test $(ruby -e "puts RUBY_VERSION" == "2.0.0")
then
  echo "  + Ruby found."
else
  echo "==> You need to install Ruby 2.0.0"
  echo "    Ruby can be downloaded from: http://www.ruby-lang.org/"
  echo "    If you want to support multiple versions of Ruby on your system, you can install: https://rvm.io/"
  exit 1
fi

# Test for Bundler
if test $(which bundle)
then
  echo "  + Bundler found."
else
  echo "==> You need to install Bundler. To install it, run:"
  echo "      gem install bundler"
  exit 1
fi

# Set up gems
echo "  + Boostrapping gems:"
echo "==============================="
bundle install
echo "==============================="
echo ""

echo "==> You're good to go!"
echo ""
echo "    Run 'bundle exec jekyll --serve --auto' to start a local development server."
echo ""